
// Navigation configuration for different user roles
export const navigationConfig = {
  owner: [
    { path: '/', labelKey: 'nav_dashboard', icon: '📊' },
    { path: '/crm', labelKey: 'nav_crm', icon: '🧩' },
    { path: '/recruitment', labelKey: 'nav_recruitment', icon: '🧑‍💼' },
    { path: '/marketing', labelKey: 'nav_marketing', icon: '🎯' },
    { path: '/tasks', labelKey: 'nav_tasks', icon: '📝' },
    { path: '/analytics', labelKey: 'nav_analytics', icon: '📈' },
    { path: '/communications', labelKey: 'nav_communications', icon: '📨' },
    { path: '/users-management', labelKey: 'nav_users', icon: '👥' },
    { path: '/students', labelKey: 'nav_students', icon: '⚽' },
    { path: '/groups', labelKey: 'nav_groups', icon: '📋' },
    { path: '/schedule', labelKey: 'nav_schedule', icon: '📅' },
    { path: '/attendance', labelKey: 'nav_attendance', icon: '✅' },
    { path: '/payments', labelKey: 'nav_payments', icon: '💰' },
    { path: '/salary-management', labelKey: 'nav_salary_management', icon: '💵' },
    { path: '/history', labelKey: 'nav_history', icon: '🕐' },
    { path: '/settings', labelKey: 'nav_settings', icon: '⚙️' },
  ],
  super_admin: [
    { path: '/', labelKey: 'nav_dashboard', icon: '📊' },
    { path: '/crm', labelKey: 'nav_crm', icon: '🧩' },
    { path: '/recruitment', labelKey: 'nav_recruitment', icon: '🧑‍💼' },
    { path: '/marketing', labelKey: 'nav_marketing', icon: '🎯' },
    { path: '/tasks', labelKey: 'nav_tasks', icon: '📝' },
    { path: '/analytics', labelKey: 'nav_analytics', icon: '📈' },  // Only owner has full analytics
    { path: '/communications', labelKey: 'nav_communications', icon: '📨' },
    { path: '/users-management', labelKey: 'nav_users', icon: '👥' },
    { path: '/students', labelKey: 'nav_students', icon: '⚽' },
    { path: '/groups', labelKey: 'nav_groups', icon: '📋' },
    { path: '/schedule', labelKey: 'nav_schedule', icon: '📅' },
    { path: '/attendance', labelKey: 'nav_attendance', icon: '✅' },
    { path: '/payments', labelKey: 'nav_payments', icon: '💰' },
    { path: '/salary-management', labelKey: 'nav_salary_management', icon: '💵' },
    { path: '/history', labelKey: 'nav_history', icon: '🕐' },
    { path: '/settings', labelKey: 'nav_settings', icon: '⚙️' },
  ],
  admin: [
    { path: '/', labelKey: 'nav_dashboard', icon: '📊' },
    { path: '/tasks', labelKey: 'nav_tasks', icon: '📝' },
    { path: '/communications', labelKey: 'nav_communications', icon: '📨' },
    { path: '/users-management', labelKey: 'nav_users', icon: '👥' },
    { path: '/students', labelKey: 'nav_students', icon: '⚽' },
    { path: '/groups', labelKey: 'nav_groups', icon: '📋' },
    { path: '/schedule', labelKey: 'nav_schedule', icon: '📅' },
    { path: '/attendance', labelKey: 'nav_attendance', icon: '✅' },
    { path: '/payments', labelKey: 'nav_payments', icon: '💰' },
    { path: '/my-salary', labelKey: 'nav_my_salary', icon: '💵' },
    // history is added dynamically if permission exists
    { path: '/settings', labelKey: 'nav_settings', icon: '⚙️' },
  ],
  accountant: [
    { path: '/', labelKey: 'nav_dashboard', icon: '📊' },
    { path: '/payments', labelKey: 'nav_payments', icon: '💰' },
    { path: '/salary-management', labelKey: 'nav_salary_management', icon: '💵' },
    { path: '/my-salary', labelKey: 'nav_my_salary', icon: '🧾' },
    { path: '/settings', labelKey: 'nav_settings', icon: '⚙️' },
  ],
  coach: [
    { path: '/', labelKey: 'nav_dashboard', icon: '🏠' },
    { path: '/schedule', labelKey: 'nav_schedule', icon: '📅' },
    { path: '/calendar', labelKey: 'nav_calendar', icon: '📆' },
    { path: '/communications', labelKey: 'nav_communications', icon: '📨' },
    { path: '/coach-analytics', labelKey: 'nav_coach_analytics', icon: '📊' },
    { path: '/attendance', labelKey: 'nav_attendance', icon: '✅' },
    { path: '/students', labelKey: 'nav_students', icon: '👥' },
    { path: '/my-salary', labelKey: 'nav_my_salary', icon: '💵' },
    { path: '/settings', labelKey: 'nav_settings', icon: '⚙️' },
  ],
  parent: [
    { path: '/', labelKey: 'nav_personal', icon: '👨‍👩‍👧' },
    { path: '/communications', labelKey: 'nav_communications', icon: '📨' },
    { path: '/calendar', labelKey: 'nav_calendar', icon: '📅' },
    { path: '/payments', labelKey: 'nav_payments', icon: '💰' },
    { path: '/settings', labelKey: 'nav_settings', icon: '⚙️' },
  ],
};

export const roleLabelKeys = {
  super_admin: 'role_sport_director',
  owner: 'role_finance_director',
  admin: 'role_admin',
  accountant: 'role_accountant',
  coach: 'role_coach',
  parent: 'role_parent',
};
