server {
    listen       80;
    server_name  localhost;

    # Обслуживание статических файлов
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Важно для SPA (React Router): если файл не найден, отдаем index.html
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики (опционально, но полезно)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root   /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
