import React, { useState } from 'react';
import { motion as Motion, AnimatePresence } from 'framer-motion';
import { Check, X, Clock, FileText, Download } from 'lucide-react';
import { exportToExcel, exportToPDF, getDateString } from '../../../utils/exportUtils';

const AttendanceList = ({ students, onAttendanceChange, t }) => {
  const [attendance, setAttendance] = useState({});
  const [isExporting, setIsExporting] = useState(false);

  const handleStatusChange = (studentId, status) => {
    const newStatus = attendance[studentId] === status ? null : status;
    setAttendance(prev => ({
      ...prev,
      [studentId]: newStatus
    }));
    if (onAttendanceChange) {
      onAttendanceChange(studentId, newStatus);
    }
  };

  const generateReport = () => {
    setIsExporting(true);
    try {
      const columns = {
        index: '#',
        student: t('student') || "Student",
        status: t('status') || "Status"
      };
      
      const dataToExport = students.map((s, i) => ({
        index: i + 1,
        student: `${s.first_name} ${s.last_name}`,
        status: attendance[s.id] ? (t(attendance[s.id]) || attendance[s.id]).toUpperCase() : '-'
      }));

      const footer = (doc) => {
        const pageSize = doc.internal.pageSize;
        const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
        const pageWidth = pageSize.width ? pageSize.width : pageSize.getWidth();
        
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text("Generated by Football Academy System", 14, pageHeight - 10);
        doc.text("Coach Signature: ____________________", pageWidth - 80, pageHeight - 10);
      };

      exportToPDF(
        dataToExport, 
        columns, 
        `attendance_report_${getDateString()}`, 
        `${t('attendanceReport') || "Attendance Report"} - ${new Date().toLocaleDateString()}`,
        footer,
        'portrait'
      );
    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setIsExporting(false);
    }
  };

  const handleExcelExport = () => {
    const dataToExport = students.map(s => ({
      first_name: s.first_name,
      last_name: s.last_name,
      status: attendance[s.id] ? (t(attendance[s.id]) || attendance[s.id]) : (t('unmarked') || 'Unmarked')
    }));

    const columns = {
      first_name: t('first_name') || 'First Name',
      last_name: t('last_name') || 'Last Name',
      status: t('status') || 'Status'
    };

    exportToExcel(dataToExport, columns, `attendance_session_${getDateString()}`);
  };

  return (
    <div className="bg-brand-gray/20 rounded-3xl p-4 md:p-6 border border-brand-gray/50">
      <div className="flex justify-between items-center mb-6">
        <h3 className="text-lg md:text-xl font-bold text-white flex items-center gap-2">
          <div className="w-2 h-6 md:h-8 bg-brand-yellow rounded-full"></div>
          {t('attendanceTracker') || "Attendance Tracker"}
        </h3>
        <div className="flex gap-2">
          <button 
            onClick={handleExcelExport}
            className="flex items-center gap-2 px-3 py-1.5 md:px-4 md:py-2 bg-green-500/10 hover:bg-green-500/20 text-green-400 rounded-2xl transition-colors border border-green-500/30"
            title="Export Excel"
          >
            <Download size={18} />
          </button>
          <button 
            onClick={generateReport}
            disabled={isExporting}
            className={`flex items-center gap-2 px-3 py-1.5 md:px-4 md:py-2 bg-brand-gray/50 hover:bg-brand-gray text-white rounded-2xl transition-colors border border-brand-gray ${isExporting ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            <FileText size={18} />
            <span className="hidden sm:inline">
              {isExporting ? (t('exporting') || "Exporting...") : (t('exportReport') || "Export Report")}
            </span>
          </button>
        </div>
      </div>

      <div className="space-y-3">
        <AnimatePresence>
          {students.map(student => (
            <Motion.div
              key={student.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="flex flex-col sm:flex-row items-center justify-between p-4 bg-brand-black/50 rounded-lg border border-brand-gray/30 hover:border-brand-yellow/30 transition-colors"
            >
              <div className="flex items-center gap-4 mb-3 sm:mb-0 w-full sm:w-auto">
                <div className="w-10 h-10 rounded-full bg-brand-gray flex items-center justify-center text-brand-yellow font-bold text-lg">
                  {student.first_name?.[0] || '?'}{student.last_name?.[0] || '?'}
                </div>
                <div>
                  <h4 className="font-semibold text-white">{student.first_name} {student.last_name}</h4>
                  <p className="text-xs text-gray-400">#{student.id}</p>
                </div>
              </div>

              <div className="flex gap-2 w-full sm:w-auto justify-center">
                <button
                  onClick={() => handleStatusChange(student.id, 'present')}
                  className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-3 rounded-lg border transition-all ${
                    attendance[student.id] === 'present'
                      ? 'bg-green-500/20 border-green-500 text-green-400'
                      : 'bg-transparent border-brand-gray text-gray-400 hover:border-green-500/50'
                  }`}
                >
                  <Check size={20} />
                  <span className="sr-only">Present</span>
                </button>

                <button
                  onClick={() => handleStatusChange(student.id, 'late')}
                  className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-3 rounded-lg border transition-all ${
                    attendance[student.id] === 'late'
                      ? 'bg-yellow-500/20 border-yellow-500 text-yellow-400'
                      : 'bg-transparent border-brand-gray text-gray-400 hover:border-yellow-500/50'
                  }`}
                >
                  <Clock size={20} />
                  <span className="sr-only">Late</span>
                </button>

                <button
                  onClick={() => handleStatusChange(student.id, 'absent')}
                  className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-3 rounded-lg border transition-all ${
                    attendance[student.id] === 'absent'
                      ? 'bg-red-500/20 border-red-500 text-red-400'
                      : 'bg-transparent border-brand-gray text-gray-400 hover:border-red-500/50'
                  }`}
                >
                  <X size={20} />
                  <span className="sr-only">Absent</span>
                </button>
              </div>
            </Motion.div>
          ))}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default AttendanceList;
